### ISSUE TITLE
.KM files will not open - download only

### ISSUE THREAD

**Issue by reidcanavan** [nextcloud/files_mindmap#98]
You can create a new mind map file, but when trying to access it after saving you are only provided the option to download.

Using version 0.0.20 on NextCloud 18.0.2

**Comment by ACTom** [comment]
Sorry, I can't reproduce.

**Comment by reidcanavan** [comment]
We have disabled the app for now because our users are not able to open the mind map files.  It always comes up as a download instead of opening.  I can only advise we are using Nextcloud 18.0.2 on CentOS 7 fully patched with PHP 7.2.

 

----- Original message -----

**Comment by ACTom** [comment]
Is your nextcloud directory read-only? When the app is installed, you need to update the mimetype configuration of nextcloud. The app will create two files in the config directory, and then call the internal update-js command to update the two files under core / js, or you can try the following two manually after installing the app: Article execution:
`occ maintenance: mimetype: update-js`
`occ files: scan`

**Comment by alexfornuto** [comment]
I was able to open newly created km files but not ones created from previous versions. The steps above resolve this for me, thanks!

Consider adding this to documentation.

**Comment by reidcanavan** [comment]
I can confirm that this works for me as well.

 

----- Original message -----

**Comment by Deltachaos** [comment]
same problem for me

**Comment by alexfornuto** [comment]
@Deltachaos Did ACTom's [fix](#issuecomment-600411411) help you?

**Comment by iWangJiaxiang** [comment]
> Is your nextcloud directory read-only? When the app is installed, you need to update the mimetype configuration of nextcloud. The app will create two files in the config directory, and then call the internal update-js command to update the two files under core / js, or you can try the following two manually after installing the app: Article execution:
> `occ maintenance: mimetype: update-js`
> `occ files: scan`

This solution saved my life!

**Comment by gustavotero7** [comment]
Same problem here, after updating to 18.x we can create mind maps but not open them again later, it just downloads the file.

Old mind maps still working well, but the new ones can't be opened again after creating it

Centos 7
Php 7.3
PostgreSQL 11
Nextlcoud 18.0.3

**Comment by alexfornuto** [comment]
@gustavotero7 did you try [the fix](https://github.com/ACTom/files_mindmap/issues/98#issuecomment-600411411) that several people said works for them?

**Comment by flaurin** [comment]
Hmmm, I ran the two strings above and the server accepted them but the problem persists. 
.km files are still downloaded instead of opened in the browser.

Nextcloud 18.0.2

sudo -u www-data php /var/www/box.laurin.xyz/occ files:scan -all
sudo -u www-data php /var/www/box.laurin.xyz/occ maintenance:mimetype:update-js

Ideas?

**Comment by ACTom** [comment]
@flaurin Is your config directory read-only? When installing this app, two files will be created in the config directory: mimetypealiases.json and mimetypemapping.json. Please check whether these two files exist. If not, please add them manually. The code is as follows:
mimetypealiases.json
`{
    "application/km": "mindmap",
    "application/x-freemind": "mindmap",
    "application/vnd.xmind.workbook": "mindmap"
}`
mimetypemapping.json:
`{
    "km": [
        "application/km"
    ],
    "mm": [
        "application/x-freemind"
    ],
    "xmind": [
        "application/vnd.xmind.workbook"
    ]
}`
Then execute the above two commands.

**Comment by flaurin** [comment]
Thanks so much for that. Now it works to open new and old .km files in the browser. (Se below what I did)
BUT, a new problem has occured: .km files that are SHARED with a link do not open. Im getting "Internal server error" when trying to open the links on another computer. 
Links created on OTHER files opens fine after sharing so its something to do with .km och the directories. 

Ideas?



This is what I did:
sudo nano /var/www/SERVERURL/config/mimetypealiases.json
{ "application/km": "mindmap", "application/x-freemind": "mindmap", "application/vnd.xmind.workbook": "mindmap" }

sudo nano /var/www/SERVERURL/config/mimetypemapping.json
{ "km": [ "application/km" ], "mm": [ "application/x-freemind" ], "xmind": [ "application/vnd.xmind.workbook" ] }

Run: 
sudo -u www-data php /var/www/SERVERURL/occ files:scan --all
and
sudo -u www-data php /var/www/SERVERURL/occ maintenance:mimetype:update-js

**Comment by flaurin** [comment]
@ACTom Did you see my post above? Im really impressed with this app (having worked with MANY during the years, far more complicated) and would deeply appreciate any hints on how to solve the sharing problem of the .km files. Thx!

**Comment by tt33tt** [comment]
> 
> 
> Thanks so much for that. Now it works to open new and old .km files in the browser. (Se below what I did)
> BUT, a new problem has occured: .km files that are SHARED with a link do not open. Im getting "Internal server error" when trying to open the links on another computer.
> Links created on OTHER files opens fine after sharing so its something to do with .km och the directories.
> 
> Ideas?
> 
> This is what I did:
> sudo nano /var/www/SERVERURL/config/mimetypealiases.json
> { "application/km": "mindmap", "application/x-freemind": "mindmap", "application/vnd.xmind.workbook": "mindmap" }
> 
> sudo nano /var/www/SERVERURL/config/mimetypemapping.json
> { "km": [ "application/km" ], "mm": [ "application/x-freemind" ], "xmind": [ "application/vnd.xmind.workbook" ] }
> 
> Run:
> sudo -u www-data php /var/www/SERVERURL/occ files:scan --all
> and
> sudo -u www-data php /var/www/SERVERURL/occ maintenance:mimetype:update-js

This worked for me, too!
@ACTom I advise to create these mimetype-entries by default. This solves the bug :-)

**Comment by michuvon** [comment]
> Is your nextcloud directory read-only? When the app is installed, you need to update the mimetype configuration of nextcloud. The app will create two files in the config directory, and then call the internal update-js command to update the two files under core / js, or you can try the following two manually after installing the app: Article execution:
> `occ maintenance: mimetype: update-js`
> `occ files: scan`

I have this same problem. But if I read this solution I do not understand a word. Could someone translate this for me?

**Comment by michuvon** [comment]
ok, the first part I still don't understand, but now I just went for the "manual way" as, after a couple of duckduckgo's I found out what occ actually is and so after a few other duckduckgo's I came up with the follwoing:

(I use a RaspberryPi with NextcloudPi 18.0.4)

login to my NCPI with SSH
enter the following command:
`sudo -u www-data php /var/www/nextcloud/occ maintenance:mimetype:update-js`

Output:
> mimetypelist.js is updated

enter the following command:
`sudo -u www-data php /var/www/nextcloud/occ files:scan --all`

Output
> Starting scan for user 1 out of 5 (USER1)
> Starting scan for user 2 out of 5 (USER2)

Exception during scan: An exception occurred while executing 'UPDATE `oc_filecache` SET `size` = ? WHERE (`fileid` = ?) AND ((`size` <> ?) OR (`size` IS NULL))' with params [6883801934, 7696, 6883801934]:
SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction
#0 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(169): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\DBALException::wrapException(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'An exception oc...')
#2 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1063): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'UPDATE `oc_file...', Array)
#3 /var/www/nextcloud/lib/private/DB/Connection.php(220): Doctrine\DBAL\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)
#4 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(203): OC\DB\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)
#5 /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(215): Doctrine\DBAL\Query\QueryBuilder->execute()
#6 /var/www/nextcloud/lib/private/Files/Cache/Cache.php(357): OC\DB\QueryBuilder\QueryBuilder->execute()
#7 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(418): OC\Files\Cache\Cache->update(7696, Array)
#8 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(410): OC\Files\Cache\Scanner->scanChildren('files/Photos/Ph...', true, 3, 7696, true)
#9 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(410): OC\Files\Cache\Scanner->scanChildren('files/Photos/Ph...', true, 3, 7643, true)
#10 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(410): OC\Files\Cache\Scanner->scanChildren('files/Photos/Ph...', true, 3, 7642, true)
#11 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(410): OC\Files\Cache\Scanner->scanChildren('files/Photos', true, 3, 7477, true)
#12 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(410): OC\Files\Cache\Scanner->scanChildren('files', true, 3, 3010, true)
#13 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(339): OC\Files\Cache\Scanner->scanChildren('', true, 3, 3009, true)
#14 /var/www/nextcloud/lib/private/Files/Utils/Scanner.php(261): OC\Files\Cache\Scanner->scan('', true, 3)
#15 /var/www/nextcloud/apps/files/lib/Command/Scan.php(151): OC\Files\Utils\Scanner->scan(‘/USER2’, true, NULL)
#16 /var/www/nextcloud/apps/files/lib/Command/Scan.php(207): OCA\Files\Command\Scan->scanFiles(‘USER2’, ‘/USER2’, Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)
#17 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/nextcloud/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/nextcloud/3rdparty/symfony/console/Application.php(915): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/nextcloud/lib/private/Console/Application.php(214): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/nextcloud/console.php(99): OC\Console\Application->run()
#24 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#25 {main}

> Starting scan for user 3 out of 5 (USER3)
> . . .

_______________________________________________________________________
Can someone tell me, what’s the error about?

The scan takes quite long, its actually still ongoing as I write this. However, I can already open the .km file in nextcloud. So seems to have worked.
Or how do you think? Did I do everything right?

**Comment by rosareven** [comment]
Chiming in to say I'm also having the same issue - clicking the .km file gives me the download prompt instead of opening the editor.

**Comment by MickaelBergem** [comment]
Running the commands posted "fixed" the issue, at the cost of erasing all previously-created mind maps. Looks like I cannot recover existing mind maps somehow, the file is now 1 byte and NextCloud doesn't have any previous version that are more than 1 byte...

**Comment by AndyScherzinger** [comment]
Works in the latest releases - you might need to force refresh the files UI in case you update from a previous version
